# Generated by Django 5.2.1 on 2025-05-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicadecancelacion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='politicadecancelacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politicadecancelacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TipoPolitica',
        ),
    ]
