# Generated by Django 5.2.1 on 2025-06-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_admin_code_attempts_usuario_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='sucursal_devolucion',
            field=models.ForeignKey(db_column='ID_Sucursal_Devolucion', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alquileres_devolucion', to='api.sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.localidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.rol'),
            preserve_default=False,
        ),
    ]
