# Generated by Django 5.2.1 on 2025-05-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_politicadecancelacion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicadecancelacion',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='politicadecancelacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
