# Generated by Django 5.2.1 on 2025-07-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alquiler_sucursal_devolucion_alter_usuario_localidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='sucursal_devolucion',
            field=models.ForeignKey(blank=True, db_column='ID_Sucursal_Devolucion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alquileres_devolucion', to='api.sucursal'),
        ),
    ]
