# Generated by Django 5.2.1 on 2025-06-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_first_name_usuario_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
    ]
