# Generated by Django 5.2.1 on 2025-05-21 04:12

import django.db.models.deletion
from django.db import migrations, models

def convert_localidad_to_foreign_key(apps, schema_editor):
    Sucursal = apps.get_model('api', 'Sucursal')
    Localidad = apps.get_model('api', 'Localidad')
    
    # Para cada sucursal existente
    for sucursal in Sucursal.objects.all():
        # Obtener o crear la localidad correspondiente
        localidad_nombre = sucursal.localidad
        localidad, created = Localidad.objects.get_or_create(nombre=localidad_nombre)
        # Actualizar la sucursal con el ID de la localidad
        sucursal.localidad_id = localidad.id
        sucursal.save()

class Migration(migrations.Migration):

    dependencies = [
       ('api', '0003_alter_politicadecancelacion_descripcion_and_more'),
    ]

    operations = [
        # Primero, renombrar la columna actual
        migrations.RenameField(
            model_name='sucursal',
            old_name='localidad',
            new_name='localidad_old',
        ),
        # Luego, agregar la nueva columna como ForeignKey
        migrations.AddField(
            model_name='sucursal',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.localidad', db_column='ID_Localidad'),
        ),
        # Ejecutar la función de conversión
        migrations.RunPython(convert_localidad_to_foreign_key),
        # Hacer que el campo sea no nulo
        migrations.AlterField(
            model_name='sucursal',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.localidad', db_column='ID_Localidad'),
        ),
        # Finalmente, eliminar la columna antigua
        migrations.RemoveField(
            model_name='sucursal',
            name='localidad_old',
        ),
    ]
