# Generated by Django 5.2.1 on 2025-07-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_alquiler_sucursal_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(db_column='nombre', max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(db_column='apellido', max_length=150, verbose_name='apellido'),
        ),
    ]
