# Generated by Django 5.2.1 on 2025-05-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rol_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
    ]
