# Generated by Django 5.2.1 on 2025-05-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reset_sequences'),
        ('api', '0008_remove_usuario_first_name_remove_usuario_last_name'),
    ]

    operations = [
    ]
