# Generated by Django 5.2.1 on 2025-05-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250527_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
